#!/bin/ruby
require 'pry' # TODO remove
require './files/dices.rb'
require './files/players.rb'
require './files/utils.rb'
require './files/score.rb'

puts "Let's play!"

players = get_players

separator

puts "GET READY, #{list_string(player_names(players))}!"

13.times do
  players.each do |player|
    puts "#{player[:name]}, it's your turn."
    puts "Hit Enter to throw!"
    gets
    saved_dices = []
    show_rows(player)

    3.times do |time|
      separator
      roll = roll_dices(5 - saved_dices.length)
      separator
      if time < 2
        keepers = pick_dices(roll)
      else
        keepers = roll
      end

      saved_dices += keepers

      break if saved_dices.length == 5
    end
    
    saved_dices.sort!
    
    puts "You have #{list_string(saved_dices)}. Let's score it."
    gets

    score_hash = score(saved_dices, player)
    if score_hash[:yahtzee] && player[:score][:yahtzee] # is 2nd yahtzee
      player[:score][:yahtzee] += score_hash[:yahtzee]
    else
      player[:score] = player[:score].merge(score_hash)
    end
    puts "Good job #{player[:name]}, you have added #{score_hash.values.first} to your score!"
    puts "You have now #{player[:score].values.sum}"
  end
  
  separator

  # end_of_round_comment(players)
end

ranked_players = players.sort_by { |player| -player[:score].values.sum }
winner = ranked_players.first
puts "Our winner is #{winner[:name]} with #{winner[:score].values.sum.to_s} points!"
puts "Then we have #{winner_list_string(ranked_players.drop(1))}"
puts "Good game!"

# puts "Game over, Julien is the winner"
